// This file is auto-generated by scripts/generate.js

import type * as types from "./types.gen.js";

/**
 * A value to send as `RequestPermissionSubject`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `RequestPermissionSubject` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingRequestPermissionSubject =
  | (types.ToolCallPermissionSubject & { type: "tool_call" })
  | (types.CommandPermissionSubject & { type: "command" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `ToolCallContent`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `ToolCallContent` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingToolCallContent =
  | (types.Content & { type: "content" })
  | (types.Diff & { type: "diff" })
  | (types.Terminal & { type: "terminal" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `ContentBlock`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `ContentBlock` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingContentBlock =
  | (types.TextContent & { type: "text" })
  | (types.ImageContent & { type: "image" })
  | (types.AudioContent & { type: "audio" })
  | (types.ResourceLink & { type: "resource_link" })
  | (types.EmbeddedResource & { type: "resource" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `DiffChange`: one of its known variants, or a
 * custom variant whose `operation` starts with `_`.
 *
 * `DiffChange` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `operation` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingDiffChange =
  | ((types.DiffPathChange & { operation: "add" }) &
      Pick<types.DiffChange, "fileType" | "mimeType" | "_meta">)
  | ((types.DiffPathChange & { operation: "delete" }) &
      Pick<types.DiffChange, "fileType" | "mimeType" | "_meta">)
  | ((types.DiffPathChange & { operation: "modify" }) &
      Pick<types.DiffChange, "fileType" | "mimeType" | "_meta">)
  | ((types.DiffPathPairChange & { operation: "move" }) &
      Pick<types.DiffChange, "fileType" | "mimeType" | "_meta">)
  | ((types.DiffPathPairChange & { operation: "copy" }) &
      Pick<types.DiffChange, "fileType" | "mimeType" | "_meta">)
  | ({ operation: string; [key: string]: unknown } & Pick<
      types.DiffChange,
      "fileType" | "mimeType" | "_meta"
    > & { operation: `_${string}` });

/**
 * A value to send as `CreateElicitationRequest`: one of its known variants, or a
 * custom variant whose `mode` starts with `_`.
 *
 * `CreateElicitationRequest` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `mode` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingCreateElicitationRequest =
  | ((types.ElicitationFormMode & { mode: "form" }) &
      Pick<types.CreateElicitationRequest, "message" | "_meta">)
  | ((types.ElicitationUrlMode & { mode: "url" }) &
      Pick<types.CreateElicitationRequest, "message" | "_meta">)
  | (((types.ElicitationSessionScope | types.ElicitationRequestScope) & {
      mode: string;
      [key: string]: unknown;
    }) &
      Pick<types.CreateElicitationRequest, "message" | "_meta"> & {
        mode: `_${string}`;
      });

/**
 * A value to send as `ElicitationPropertySchema`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `ElicitationPropertySchema` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingElicitationPropertySchema =
  | (types.StringPropertySchema & { type: "string" })
  | (types.NumberPropertySchema & { type: "number" })
  | (types.IntegerPropertySchema & { type: "integer" })
  | (types.BooleanPropertySchema & { type: "boolean" })
  | (types.MultiSelectPropertySchema & { type: "array" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `MultiSelectItems`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `MultiSelectItems` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingMultiSelectItems =
  | (types.StringMultiSelectItems & { type: "string" })
  | types.TitledMultiSelectItems
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `AuthMethod`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `AuthMethod` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingAuthMethod =
  | (types.AuthMethodTerminal & { type: "terminal" })
  | (types.AuthMethodAgent & { type: "agent" })
  | (({ type: string; [key: string]: unknown } & {
      methodId: types.AuthMethodId;
      name: string;
    }) & { type: `_${string}` });

/**
 * A value to send as `SessionConfigOption`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `SessionConfigOption` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingSessionConfigOption =
  | ((types.SessionConfigSelect & { type: "select" }) &
      Pick<
        types.SessionConfigOption,
        "configId" | "name" | "description" | "category" | "_meta"
      >)
  | ((types.SessionConfigBoolean & { type: "boolean" }) &
      Pick<
        types.SessionConfigOption,
        "configId" | "name" | "description" | "category" | "_meta"
      >)
  | ({ type: string; [key: string]: unknown } & Pick<
      types.SessionConfigOption,
      "configId" | "name" | "description" | "category" | "_meta"
    > & { type: `_${string}` });

/**
 * A value to send as `AvailableCommandInput`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `AvailableCommandInput` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingAvailableCommandInput =
  | (types.TextCommandInput & { type: "text" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `NesSuggestion`: one of its known variants, or a
 * custom variant whose `kind` starts with `_`.
 *
 * `NesSuggestion` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `kind` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingNesSuggestion =
  | (types.NesEditSuggestion & { kind: "edit" })
  | (types.NesJumpSuggestion & { kind: "jump" })
  | (types.NesRenameSuggestion & { kind: "rename" })
  | (types.NesSearchAndReplaceSuggestion & { kind: "searchAndReplace" })
  | (({ kind: string; [key: string]: unknown } & {
      suggestionId: types.NesSuggestionId;
    }) & { kind: `_${string}` });

/**
 * A value to send as `SessionUpdate`: one of its known variants, or a
 * custom variant whose `sessionUpdate` starts with `_`.
 *
 * `SessionUpdate` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `sessionUpdate` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingSessionUpdate =
  | (types.ContentChunk & { sessionUpdate: "user_message_chunk" })
  | (types.UserMessage & { sessionUpdate: "user_message" })
  | (types.ContentChunk & { sessionUpdate: "agent_message_chunk" })
  | (types.AgentMessage & { sessionUpdate: "agent_message" })
  | (types.ContentChunk & { sessionUpdate: "agent_thought_chunk" })
  | (types.AgentThought & { sessionUpdate: "agent_thought" })
  | (types.StateUpdate & { sessionUpdate: "state_update" })
  | (types.ToolCallContentChunk & { sessionUpdate: "tool_call_content_chunk" })
  | (types.ToolCallUpdate & { sessionUpdate: "tool_call_update" })
  | (types.TerminalUpdate & { sessionUpdate: "terminal_update" })
  | (types.TerminalOutputChunk & { sessionUpdate: "terminal_output_chunk" })
  | (types.PlanUpdate & { sessionUpdate: "plan_update" })
  | (types.PlanRemoved & { sessionUpdate: "plan_removed" })
  | (types.AvailableCommandsUpdate & {
      sessionUpdate: "available_commands_update";
    })
  | (types.ConfigOptionUpdate & { sessionUpdate: "config_option_update" })
  | (types.SessionInfoUpdate & { sessionUpdate: "session_info_update" })
  | (types.UsageUpdate & { sessionUpdate: "usage_update" })
  | (types.Notice & { sessionUpdate: "notice" })
  | (types.CompactionUpdate & { sessionUpdate: "compaction_update" })
  | (types.CompactionSummaryChunk & {
      sessionUpdate: "compaction_summary_chunk";
    })
  | (types.SubagentUpdate & { sessionUpdate: "subagent_update" })
  | (types.SessionMessage & { sessionUpdate: "session_message" })
  | (types.SessionMessageChunk & { sessionUpdate: "session_message_chunk" })
  | ({ sessionUpdate: string; [key: string]: unknown } & {
      sessionUpdate: `_${string}`;
    });

/**
 * A value to send as `StateUpdate`: one of its known variants, or a
 * custom variant whose `state` starts with `_`.
 *
 * `StateUpdate` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `state` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingStateUpdate =
  | (types.RunningStateUpdate & { state: "running" })
  | (types.IdleStateUpdate & { state: "idle" })
  | (types.RequiresActionStateUpdate & { state: "requires_action" })
  | (types.UnknownStateUpdate & { state: "unknown" })
  | ({ state: string; [key: string]: unknown } & { state: `_${string}` });

/**
 * A value to send as `PlanUpdateContent`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `PlanUpdateContent` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingPlanUpdateContent =
  | (types.PlanItems & { type: "items" })
  | (types.PlanFile & { type: "file" })
  | (types.PlanMarkdown & { type: "markdown" })
  | (({ type: string; [key: string]: unknown } & { planId: types.PlanId }) & {
      type: `_${string}`;
    });

/**
 * A value to send as `McpServer`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `McpServer` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingMcpServer =
  | (types.McpServerHttp & { type: "http" })
  | (types.McpServerAcp & { type: "acp" })
  | (types.McpServerStdio & { type: "stdio" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `ReplayFrom`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `ReplayFrom` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingReplayFrom =
  | (types.ReplayFromStart & { type: "start" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `SetSessionConfigOptionRequest`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `SetSessionConfigOptionRequest` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingSetSessionConfigOptionRequest =
  | (({ type: "id" } & { value: types.SessionConfigValueId }) &
      Pick<
        types.SetSessionConfigOptionRequest,
        "sessionId" | "configId" | "_meta"
      >)
  | (({ type: "boolean" } & { value: boolean }) &
      Pick<
        types.SetSessionConfigOptionRequest,
        "sessionId" | "configId" | "_meta"
      >)
  | (({ type: string; [key: string]: unknown } & { value: unknown }) &
      Pick<
        types.SetSessionConfigOptionRequest,
        "sessionId" | "configId" | "_meta"
      > & { type: `_${string}` });

/**
 * A value to send as `RequestPermissionOutcome`: one of its known variants, or a
 * custom variant whose `outcome` starts with `_`.
 *
 * `RequestPermissionOutcome` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `outcome` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingRequestPermissionOutcome =
  | { outcome: "cancelled" }
  | (types.SelectedPermissionOutcome & { outcome: "selected" })
  | ({ outcome: string; [key: string]: unknown } & { outcome: `_${string}` });

/**
 * A value to send as `CreateElicitationResponse`: one of its known variants, or a
 * custom variant whose `action` starts with `_`.
 *
 * `CreateElicitationResponse` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `action` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingCreateElicitationResponse =
  | ((types.ElicitationAcceptAction & { action: "accept" }) &
      Pick<types.CreateElicitationResponse, "_meta">)
  | ({ action: "decline" } & Pick<types.CreateElicitationResponse, "_meta">)
  | ({ action: "cancel" } & Pick<types.CreateElicitationResponse, "_meta">)
  | ({ action: string; [key: string]: unknown } & Pick<
      types.CreateElicitationResponse,
      "_meta"
    > & { action: `_${string}` });

// Compile-time check: every outgoing type is a value of its open union.
type IsSendableAs<Union, Outgoing extends Union> = [Union, Outgoing];
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type OutgoingTypesAreSendable = [
  IsSendableAs<
    types.RequestPermissionSubject,
    OutgoingRequestPermissionSubject
  >,
  IsSendableAs<types.ToolCallContent, OutgoingToolCallContent>,
  IsSendableAs<types.ContentBlock, OutgoingContentBlock>,
  IsSendableAs<types.DiffChange, OutgoingDiffChange>,
  IsSendableAs<
    types.CreateElicitationRequest,
    OutgoingCreateElicitationRequest
  >,
  IsSendableAs<
    types.ElicitationPropertySchema,
    OutgoingElicitationPropertySchema
  >,
  IsSendableAs<types.MultiSelectItems, OutgoingMultiSelectItems>,
  IsSendableAs<types.AuthMethod, OutgoingAuthMethod>,
  IsSendableAs<types.SessionConfigOption, OutgoingSessionConfigOption>,
  IsSendableAs<types.AvailableCommandInput, OutgoingAvailableCommandInput>,
  IsSendableAs<types.NesSuggestion, OutgoingNesSuggestion>,
  IsSendableAs<types.SessionUpdate, OutgoingSessionUpdate>,
  IsSendableAs<types.StateUpdate, OutgoingStateUpdate>,
  IsSendableAs<types.PlanUpdateContent, OutgoingPlanUpdateContent>,
  IsSendableAs<types.McpServer, OutgoingMcpServer>,
  IsSendableAs<types.ReplayFrom, OutgoingReplayFrom>,
  IsSendableAs<
    types.SetSessionConfigOptionRequest,
    OutgoingSetSessionConfigOptionRequest
  >,
  IsSendableAs<
    types.RequestPermissionOutcome,
    OutgoingRequestPermissionOutcome
  >,
  IsSendableAs<
    types.CreateElicitationResponse,
    OutgoingCreateElicitationResponse
  >,
];
