// This file is auto-generated by scripts/generate.js

import type * as types from "./types.gen.js";

/**
 * A value to send as `CreateElicitationRequest`: one of its known variants, or a
 * custom variant whose `mode` starts with `_`.
 *
 * `CreateElicitationRequest` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `mode` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingCreateElicitationRequest =
  | ((types.ElicitationFormMode & { mode: "form" }) &
      Pick<types.CreateElicitationRequest, "message" | "_meta">)
  | ((types.ElicitationUrlMode & { mode: "url" }) &
      Pick<types.CreateElicitationRequest, "message" | "_meta">)
  | (((types.ElicitationSessionScope | types.ElicitationRequestScope) & {
      mode: string;
      [key: string]: unknown;
    }) &
      Pick<types.CreateElicitationRequest, "message" | "_meta"> & {
        mode: `_${string}`;
      });

/**
 * A value to send as `ElicitationPropertySchema`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `ElicitationPropertySchema` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingElicitationPropertySchema =
  | (types.StringPropertySchema & { type: "string" })
  | (types.NumberPropertySchema & { type: "number" })
  | (types.IntegerPropertySchema & { type: "integer" })
  | (types.BooleanPropertySchema & { type: "boolean" })
  | (types.MultiSelectPropertySchema & { type: "array" })
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `MultiSelectItems`: one of its known variants, or a
 * custom variant whose `type` starts with `_`.
 *
 * `MultiSelectItems` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `type` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingMultiSelectItems =
  | (types.StringMultiSelectItems & { type: "string" })
  | types.TitledMultiSelectItems
  | ({ type: string; [key: string]: unknown } & { type: `_${string}` });

/**
 * A value to send as `StateUpdate`: one of its known variants, or a
 * custom variant whose `state` starts with `_`.
 *
 * `StateUpdate` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `state` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 *
 * @experimental
 */
export type OutgoingStateUpdate =
  | (types.RunningStateUpdate & { state: "running" })
  | (types.IdleStateUpdate & { state: "idle" })
  | (types.RequiresActionStateUpdate & { state: "requires_action" })
  | (types.UnknownStateUpdate & { state: "unknown" })
  | ({ state: string; [key: string]: unknown } & { state: `_${string}` });

/**
 * A value to send as `CreateElicitationResponse`: one of its known variants, or a
 * custom variant whose `action` starts with `_`.
 *
 * `CreateElicitationResponse` itself is for values you receive, so it also accepts
 * future ACP variants: any object with a string `action` fits it,
 * including a known variant with a misspelled or missing field. This type
 * catches those mistakes at compile time. Custom variants stay
 * expressible under a `_`-prefixed tag, which the protocol requires for
 * implementation-specific values.
 *
 * Extensible unions nested inside the value keep their open types: type
 * the nested values you build with their own `Outgoing` types.
 */
export type OutgoingCreateElicitationResponse =
  | ((types.ElicitationAcceptAction & { action: "accept" }) &
      Pick<types.CreateElicitationResponse, "_meta">)
  | ({ action: "decline" } & Pick<types.CreateElicitationResponse, "_meta">)
  | ({ action: "cancel" } & Pick<types.CreateElicitationResponse, "_meta">)
  | ({ action: string; [key: string]: unknown } & Pick<
      types.CreateElicitationResponse,
      "_meta"
    > & { action: `_${string}` });

// Compile-time check: every outgoing type is a value of its open union.
type IsSendableAs<Union, Outgoing extends Union> = [Union, Outgoing];
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type OutgoingTypesAreSendable = [
  IsSendableAs<
    types.CreateElicitationRequest,
    OutgoingCreateElicitationRequest
  >,
  IsSendableAs<
    types.ElicitationPropertySchema,
    OutgoingElicitationPropertySchema
  >,
  IsSendableAs<types.MultiSelectItems, OutgoingMultiSelectItems>,
  IsSendableAs<types.StateUpdate, OutgoingStateUpdate>,
  IsSendableAs<
    types.CreateElicitationResponse,
    OutgoingCreateElicitationResponse
  >,
];
